% init environment

env_vars = utils.env(File='.env');
init_python(env_vars);
init_guilda(env_vars);
solver = py.importlib.import_module('solver_wrapper');

% create power network

net = network_2bus2gen();
net.initialize();
x_init = net.x_equilibrium;
x_init(1) = x_init(1) + pi / 6;

% simulation

tend = 20;
sim_res = net.simulate([0, tend], 'x0_sys', x_init);
sim_t = sim_res.t;

% resample
omega = 2 * 60 * pi;
t = 0:1/30:tend;
t = t';
x = [
    interp1(sim_t, sim_res.X{1}.delta, t, 'linear'), ...
    interp1(sim_t, sim_res.X{1}.omega, t, 'linear') * omega, ...
    interp1(sim_t, sim_res.X{2}.delta, t, 'linear'), ...
    interp1(sim_t, sim_res.X{2}.omega, t, 'linear') * omega
];

% identify

factor = 1.1;

gen1 = net.a_bus{1}.component;
gen2 = net.a_bus{2}.component;

% reduced admittance

Xp = diag([
  gen1.parameter.Xd, ...
  gen2.parameter.Xd
]);
Y = net.get_admittance_matrix();
G = Xp - 1i * (Xp * conj(Y) * Xp);
Y_red = -1i * (G ^ -1);

Y_red_12 = Y_red(1, 2);

% prepare necessary parameters
% TODO pass the whole reduced matrix

all_parameters_values = struct( ...
    omega_0 = net.omega0, ...
    ...
    M_1 = gen1.parameter.M, ...
    D_1 = gen1.parameter.D, ...
    V_field_1 = gen1.u_equilibrium(1), ...
    P_mech_1 = gen1.u_equilibrium(2), ...
    ...
    M_2 = gen2.parameter.M * factor, ...
    D_2 = gen2.parameter.D * factor, ...
    V_field_2 = gen2.u_equilibrium(1) * factor, ...
    P_mech_2 = gen2.u_equilibrium(2) * factor, ...
    ...
    G_11 = real(Y_red(1, 1)), ...
    G_22 = real(Y_red(2, 2)), ...
    G_12 = real(Y_red_12) * factor, ...
    B_12 = imag(Y_red_12) * factor ...
);

all_parameters = fieldnames(all_parameters_values);

normal_parameters = {
    "M_2", ...
    "D_2", ...
    "V_field_2", ...
};

special_parameters = {
    "P_mech_2", ...
    "G_12", ...
    "B_12", ...
};

clamp_parameters = {
    "M_2", ...
    "D_2", ...
    "V_field_2", ...
    "P_mech_2", ...
};

% create ground truth parameter struct for convenience

ground_truth = struct();
for i = 1:3 
    ground_truth.(normal_parameters{i}) = ...
        all_parameters_values.(normal_parameters{i}) / factor;
end
for i = 1:3 
    ground_truth.(special_parameters{i}) = ...
        all_parameters_values.(special_parameters{i}) / factor;
end

% pack network informations
all_inputs = struct(y = zeros(4, 1));
nw_func = func2str(@network_2bus2gen_ode);
nw_path = which(nw_func);

% trace

s_params = solver.ScenarioParameters( ...
    params = utils.mat2py(all_parameters_values), ...
    inputs = utils.mat2py(all_inputs), ...
    network_path = nw_path, ...
    network_name = nw_func, ...
    ...
    t = py.numpy.array(t), ...
    x0 = py.numpy.array(x_init), ...
    true_x = py.numpy.array(x), ...
    ...
    all_params = utils.mat2py(all_parameters), ...
    normal_params = utils.mat2py(normal_parameters), ...
    special_params = utils.mat2py(special_parameters), ...
    clamp_params = utils.mat2py(clamp_parameters), ...
    observable_y_indices = py.numpy.array(0:1, dtype="int") ... % for python slice
);

% nn solver parameters

sol_params = solver.SolverParameters( ...
    device = 'cpu', ...
    optim_factory = solver.default_optim_factory, ...
    batch_size = py.int(20), ...
    batch_time = py.int(30), ...
    ode_params = py.dict(method = 'rk4') ...
);

% init estimator

model = solver.create_estimator( ...
    s_params, ...
    sol_params ...
);

model.init();
params = utils.py2mat(model.get_current_params());

% training progress

disp('Ground Truth:');
disp(ground_truth);

disp('Training...');

for itr = 0:1000

    if mod(itr, 5) == 0
        disp('Parameters:');
        disp(params);
        loss = model.evaluate();
        fprintf('Total Loss: %.12f\n', loss);
    end

    start = datetime('now');
    iter_res = model.iterate();
    iter_res = cell(iter_res);
    loss = iter_res{1};
    grad_norm = iter_res{2};
    
    dur = datetime('now') - start;
    params = utils.py2mat(model.get_current_params());

    fprintf( ...
        'Iteration %d | Loss: %.12f | Grad Norm: %.12f | Time Elapsed: %.4fs\n', ...
        itr, loss, grad_norm, seconds(dur) ...
    );

    if loss < 4e-10
        disp('Converged.')
        disp(params)
        break
    end

end
